accessing
primary
"emptySet / not / and / nand / or / implies / impliesBi / notFree / forAll / exists/ existsu / existsStar / equals / subset / member/ intersection / squareBrackets / curlyBraces / angBrackets /"
	
"not / forAll / subset / parentheses / notFree  / exists / existsStar / equals / member/ label2" 

^ "not / forAll / exists / existsu / existsStar /" equals "/ notEquals/ member / union/ subset/ notFree / s / label2" "/ parentheses"